#FSR Autogenerated Content. DO NOT DELETE
from .containers import list_containers, inspect_container, start_container, stop_container, remove_container, create_container, restart_container, kill_container, container_logs, rename_container, prune_containers, exec_container
from .images import list_images, pull_image, inspect_image, remove_image, tag_image, prune_images
from .networks import list_networks, inspect_network, create_network, connect_network, disconnect_network, remove_network, prune_networks
from .volumes import list_volumes, inspect_volume, create_volume, remove_volume, prune_volumes
from .system_ops import get_version, get_info, system_df, system_events

supported_operations = {
    'list_containers': list_containers,
    'inspect_container': inspect_container,
    'start_container': start_container,
    'stop_container': stop_container,
    'remove_container': remove_container,
    'create_container': create_container,
    'restart_container': restart_container,
    'kill_container': kill_container,
    'container_logs': container_logs,
    'rename_container': rename_container,
    'prune_containers': prune_containers,
    'exec_container': exec_container,
    'list_images': list_images,
    'pull_image': pull_image,
    'inspect_image': inspect_image,
    'remove_image': remove_image,
    'tag_image': tag_image,
    'prune_images': prune_images,
    'list_networks': list_networks,
    'inspect_network': inspect_network,
    'create_network': create_network,
    'connect_network': connect_network,
    'disconnect_network': disconnect_network,
    'remove_network': remove_network,
    'prune_networks': prune_networks,
    'list_volumes': list_volumes,
    'inspect_volume': inspect_volume,
    'create_volume': create_volume,
    'remove_volume': remove_volume,
    'prune_volumes': prune_volumes,
    'get_version': get_version,
    'get_info': get_info,
    'system_df': system_df,
    'system_events': system_events,
}